### ISSUE TITLE
Commit messages missing useful detail

### ISSUE THREAD

**Issue by rossigee** [bluebrown/kobold#68]
Would be great if commit messages could more information on the change made.

Currently, my commit log history for kobold-managed repos contains `chore(kobold): reponame` repeated for each commit. If it also noted which tags have changed I wouldn't have to drill into each commit to determine which one I'm looking for.

**Comment by bluebrown** [comment]
Yeah, in my first implementation the user could supply their own template and range over the changes. 

n V2 I ignored it at first but people wanted it. So what is there isnt ideal.  In the perfect world we probably bring the template back.

Because the way the message is currently, is more or less from another user PR. So what you consider useless is maybe exactly what someone else wants. A template would maybe satisfy both.

**Comment by bluebrown** [comment]
Also this one here https://github.com/bluebrown/kobold/blob/d77d8770d849273edb42fff63fcb3ddae81292ab/krm/filter.go#L108

It is there because I was anticipating commit messages at this point. I knew from my first implementation that you want to capture the position of the image, when doing good commit messages.  Because you can have the same image multiple times, say a migration job and the apllication itself use the same image with a different command.

So in my opinion, if you want to do it correct, you need to capture some more context, like file and even more specific position in the file, say container document index, and container name.

**Comment by bluebrown** [comment]
But then on the other hand, too much details is maybe also pointless. I can just look at the commit itself. Anything I write in the body and not the commit title, I cannot view in the ui anyway. At least not in mine.

But then were is the line? Like can you drop the entire body with that argumentation?  If so then the title is capped to 50 chars, so cant pack too much info in there either. 

This kind of thinking was why v2 didnt even have any image names or anything in the title. Title is too short to be useful. body is not useful because I need to open the commit to see it, in which case I can see the changes itself.

**Comment by rossigee** [comment]
> So what you consider useless is maybe exactly what someone else wants. A template would maybe satisfy both.

Agreed. That would be the ideal solution.

**Comment by bluebrown** [comment]
I like to keep the issue open under the points I have mentioned. Doesnt mean to you have to be invloved but I dont want to repeat myself somewhere else. The issue itself is the right place too, in my opinion.
